# Generated by Django 3.1.2 on 2021-01-25 07:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QXgs_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qxgs_name', models.CharField(max_length=50, unique=True, verbose_name='旗下公司名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '旗下公司名称',
                'verbose_name_plural': '旗下公司名称',
            },
        ),
        migrations.CreateModel(
            name='QXgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('qxgs_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qxgs.qxgs_name', to_field='qxgs_name', verbose_name='旗下公司名称')),
            ],
            options={
                'verbose_name': '旗下公司',
                'verbose_name_plural': '旗下公司',
            },
        ),
    ]
