# Generated by Django 3.1.2 on 2021-01-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qxgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qxgs',
            name='qxgs_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qxgs.qxgs_name', verbose_name='旗下公司名称'),
        ),
    ]
