# Generated by Django 3.1.5 on 2021-01-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qxgs', '0002_auto_20210125_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qxgs',
            name='qxgs_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qxgs.qxgs_name', unique=True, verbose_name='旗下公司名称'),
        ),
    ]
