# Generated by Django 3.1.5 on 2021-01-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qxgs', '0003_auto_20210131_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qxgs',
            name='qxgs_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qxgs.qxgs_name', verbose_name='旗下公司名称'),
        ),
    ]
