# Generated by Django 3.1.5 on 2021-02-01 14:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qxgs', '0004_auto_20210131_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='qxgs',
            name='img',
            field=models.ImageField(default=1212, upload_to='cover_img/%Y%m%d', verbose_name='封面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qxgs',
            name='simple_content',
            field=models.CharField(default=1212, max_length=50, verbose_name='公司简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qxgs',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='公司介绍'),
        ),
        migrations.AlterField(
            model_name='qxgs',
            name='qxgs_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='旗下公司名称'),
        ),
        migrations.DeleteModel(
            name='QXgs_Name',
        ),
    ]
