# Generated by Django 3.1.5 on 2021-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qxgs', '0005_auto_20210201_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qxgs',
            name='simple_content',
            field=models.TextField(max_length=1000, verbose_name='公司简介'),
        ),
    ]
