# Generated by Django 3.1.5 on 2021-02-05 19:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cp_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_type', models.CharField(max_length=50, unique=True, verbose_name='产品类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('img', models.ImageField(upload_to='cover_img/%Y%m%d', verbose_name='封面')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
            },
        ),
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=50, unique=True, verbose_name='产品名称')),
                ('img', models.ImageField(upload_to='cover_img/%Y%m%d', verbose_name='封面')),
                ('option', models.BooleanField(verbose_name='是否上首页(六个)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpzx.cp_type', verbose_name='产品类型')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
    ]
