# Generated by Django 3.1.5 on 2021-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpzx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_type',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='内容'),
        ),
    ]
