# Generated by Django 3.1.2 on 2021-01-26 03:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XXgk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xxgk_type', models.CharField(choices=[('zdsx', '重大事项'), ('rczp', '人才招聘'), ('jtgg', '集团公告'), ('tzzgx', '投资者关系')], max_length=50, verbose_name='类型')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_time', models.DateField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '信息公开',
                'verbose_name_plural': '信息公开',
            },
        ),
    ]
