# Generated by Django 3.1.5 on 2021-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxgk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgk',
            name='xxgk_type',
            field=models.CharField(choices=[('rczp', '人才招聘'), ('jtgg', '集团公告'), ('tzzgx', '投资者关系')], max_length=50, verbose_name='类型'),
        ),
    ]
