# Generated by Django 3.1.5 on 2021-02-03 15:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxgk', '0002_auto_20210131_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='XXgk_GG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公告标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_time', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '集团公告',
                'verbose_name_plural': '集团公告',
            },
        ),
        migrations.CreateModel(
            name='XXgk_RC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_time', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '人才招聘',
                'verbose_name_plural': '人才招聘',
            },
        ),
        migrations.DeleteModel(
            name='XXgk',
        ),
    ]
