# Generated by Django 3.1.5 on 2021-01-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwzx', '0003_syimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SYNew',
        ),
        migrations.AlterField(
            model_name='syimg',
            name='published_time',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
