# Generated by Django 3.1.5 on 2021-02-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwzx', '0007_auto_20210130_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HYNew',
        ),
    ]
