# Generated by Django 3.1.5 on 2021-02-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwzx', '0008_delete_hynew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgnew',
            options={'verbose_name': '图片新闻', 'verbose_name_plural': '图片新闻'},
        ),
    ]
