# Generated by Django 3.1.5 on 2021-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SYImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cover_img/%Y%m%d', verbose_name='首页图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_time', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '首页图片',
                'verbose_name_plural': '首页图片',
            },
        ),
    ]
