# Generated by Django 3.1.2 on 2021-01-19 09:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GYwm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gywm_type', models.CharField(choices=[('jtjj', '集团简介'), ('jtgc', '集团高层'), ('zzjg', '组织机构'), ('zyyw', '主营业务'), ('ppxx', '品牌形象')], max_length=50, verbose_name='类型')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
            },
        ),
    ]
