# Generated by Django 3.1.5 on 2021-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gywm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gywm',
            name='img',
            field=models.ImageField(default=121, upload_to='cover_img/%Y%m%d', verbose_name='照片(用于品牌形象和集团高层)'),
            preserve_default=False,
        ),
    ]
