# Generated by Django 3.1.5 on 2021-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gywm', '0005_gywm_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gywm',
            name='img',
            field=models.ImageField(upload_to='cover_img/%Y%m%d', verbose_name='照片(用于品牌形象和集团高层)'),
        ),
    ]
