# Generated by Django 3.1.5 on 2021-02-03 11:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gywm', '0007_auto_20210202_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='GYwm_GC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='领导姓名')),
                ('img', models.ImageField(upload_to='cover_img/%Y%m%d', verbose_name='领导照片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='领导介绍')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公司高层',
                'verbose_name_plural': '公司高层',
            },
        ),
        migrations.CreateModel(
            name='GYwm_XX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='品牌名称')),
                ('img', models.ImageField(upload_to='cover_img/%Y%m%d', verbose_name='品牌照片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='品牌介绍')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品牌介绍',
                'verbose_name_plural': '品牌介绍',
            },
        ),
        migrations.RemoveField(
            model_name='gywm',
            name='img',
        ),
        migrations.AlterField(
            model_name='gywm',
            name='gywm_type',
            field=models.CharField(choices=[('jtjj', '集团简介'), ('zzjg', '组织机构'), ('zyyw', '主营业务')], max_length=50, verbose_name='类型'),
        ),
    ]
