# Generated by Django 3.1.5 on 2021-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gywm', '0008_auto_20210203_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gywm_gc',
            options={'verbose_name': '集团高层', 'verbose_name_plural': '集团高层'},
        ),
        migrations.AlterField(
            model_name='gywm_gc',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='领导姓名(用于后台辨认)'),
        ),
        migrations.AlterField(
            model_name='gywm_xx',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='品牌名称(用于后台辨认)'),
        ),
    ]
